[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.5.10"
authors = ["Niko Leskinen <niko.leskinen@fmi.fi>"]
license-file = "LICENSE"


[workspace.dependencies]
ndarray = "0.17"
numpy = {version = "0.27"}
